version: '3.8'

services:
  kvservice:
    build:
      context: .
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: kvservice-db
      CONFIG_PATH: ${CONFIG_PATH}
    ports:
      - "8080:8080"
    depends_on:
      kvservice-db:
        condition: service_healthy
    networks:
      - appnet

  kvservice-db:
    image: postgres:16
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - appnet                  

volumes:
  db-data:

networks:
  appnet:
    driver: bridge               
