env: prod

postgres:
  migrations_dir: "./migrations"
  pool:
    max_conns: 8
    max_conn_lifetime: 2h
    connect_timeout: 25s

http:
  addr: ":8080"
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 60s